### PR TITLE
doc(README.md): use https for online OpenCC

### PR DESCRIPTION
**Pull request by yxliang01**
Since https protocol is supported, https should be used instead of http.

### CODE REVIEW

**Comment by sgalal** [comment]
Besides, I found that recently connection to the website is very slow. Sometimes I cannot even connect to the website. And it is the same for <https://byvoid.com/>. I think we need some kind of configuration.

**Comment by yxliang01** [comment]
@sgalal I can connect very quickly. Possibly related to your network?

**Comment by sgalal** [comment]
> @sgalal I can connect very quickly. Possibly related to your network?

I found the problem and opened a new issue for that: #354

**Comment by yxliang01** [comment]
Interesting. You have IPv6 setup on your end? If so, then #354 might be the cause. (I thought IPv6 is still not so common nowadays)

**Comment by lotem** [comment]
Merged. Thanks.

**Pull request merged**
