### PR TITLE
Check offset bounds in BinaryDict::NewFromFile method

### PR DESCRIPTION
**Pull request by epico**

### CODE REVIEW

**Comment by BYVoid** [comment]
Closing obsolete pull requests.

**Comment by epico** [comment]
The crash still happens with opencc_dict tool.

```bash
$ opencc_dict -i keyoffsetPOC -o temp.txt -f ocd -t text
$ opencc_dict -i ValueOffsetPOC -o temp.txt -f ocd -t text
```

Could you reopen this pull request?

Then I can rebase this security patch, thanks.

**Comment by sgalal** [comment]
@epico Thank you. Would you please make another pull request? It seems that this one cannot be reopened.

**Comment by epico** [comment]
@sgalal, Thanks. I just created another pull request.

URL: https://github.com/BYVoid/OpenCC/pull/560

**Comment by BYVoid** [comment]
Merged. Thanks.

**Pull request closed without merging**
