### PR TITLE
Feature/python cicd

### PR DESCRIPTION
**Pull request by mingruimingrui**
## Description

This pull request adds a github action that would automatically build and upload `OpenCC` python packages to PyPI.
The goal is to make the process of deployment smoother and much less of a hassle than it is right now.

Currently, the action is setup to be triggered manually (though it can be modified to be executed on new releases etc.).
Just 1 additional thing would need to be done. @BYVoid @sgalal would have to help configure the package secret `PYPI_TOKEN`.

This was a long-overdue feature that I've only just had time to work on.
It was briefly mentioned on https://github.com/BYVoid/OpenCC/issues/477.

## Changes
- Added new github action `Build and upload python package to PyPI`
- Added new shell scripts to facilitate the building and uploading of python packages
  - release-pypi-linux.sh
  - release-pypi-macos.sh
  - release-pypi-windows.sh
- Removed previous helper scripts used for python packaging.
  - bdist_array.sh
  - bdist_array.cmd
  - BUILD.md
  - python/Dockerfile.posix

### CODE REVIEW

**Comment by sgalal** [comment]
Looks good! Since I do not have access to PyPI I cannot get the token. Need help from @BYVoid

**Comment by BYVoid** [comment]
Thank you very much. @mingruimingrui, since you have the PyPI admin access, can you suggest how to set up the `PYPI_TOKEN`?

**Comment by mingruimingrui** [comment]
@BYVoid Thanks, however, I can't add the secret to this repository.
I'll add some instructions to help you out.

1. Create a new token at OpenCC PyPI repository settings.
  https://pypi.org/manage/project/opencc/settings/
  image
2. Navigate to OpenCC GitHub repository settings and find the secrets in the sidebar.
https://github.com/BYVoid/OpenCC/settings/secrets
3. There should be some `New Secret` button. Use it to add the `PYPI_TOKEN` secret.
4. Make sure the name is `PYPI_TOKEN` and the value is the token generated from `PyPI`.
Screenshot 2020-08-11 at 5 34 22 PM

**Comment by BYVoid** [comment]
Thanks. Done.

**Pull request merged**
