### PR TITLE
Added few Traditional Chinese Characters into converting list.

### PR DESCRIPTION
**Pull request by etonline**
Contribute to the converting list.

### CODE REVIEW

**Comment by etonline** [comment]
Hm, I guess failed AppVeyor test isn't issue from my end?

**Comment by BYVoid** [comment]
Not all pairs are valid. 「犭」is not simplified.

**Comment by BYVoid** [comment]
Not all pairs are valid. 「犭」is not simplified.

**Comment by etonline** [comment]
@BYVoid Do you mean that 犭 does not exists in Simplified Chinese at all, so no conversion needed?

**Pull request closed without merging**
